# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('pmipv6', ['core'])
    module.source = [
        'model/binding-cache.cc',
        'model/binding-update-list.cc',
        'model/identifier.cc',
        'model/ipv6-mobility.cc',
        'model/ipv6-mobility-demux.cc',
        'model/ipv6-mobility-header.cc',
        'model/ipv6-mobility-l4-protocol.cc',
        'model/ipv6-mobility-option.cc',
        'model/ipv6-mobility-option-demux.cc',
        'model/ipv6-mobility-option-header.cc',
        'model/ipv6-static-source-routing.cc',
        'model/ipv6-tunnel-l4-protocol.cc',
        'model/pmipv6-agent.cc',
        'model/pmipv6-lma.cc',
        'model/pmipv6-mag.cc',
        'model/pmipv6-mag-notifier.cc',
        'model/pmipv6-prefix-pool.cc',
        'model/pmipv6-profile.cc',
        'model/tunnel-net-device.cc',
        'model/unicast-radvd.cc',
        'model/unicast-radvd-interface.cc',
        'model/regular-unicast-radvd.cc',
        'model/lte-unicast-radvd.cc',
        'model/flow-binding-list.cc',
        'model/flow-interface-list.cc',
        'model/traffic-selector.cc',
        'model/ipv6-flow-routing.cc',
        'model/ipv6-user-flow-routing.cc',
        'model/flow-manager.cc',
        'helper/ipv6-static-source-routing-helper.cc',
        'helper/pmipv6-helper.cc',
        'helper/ipv6-flow-routing-helper.cc',
        'helper/ipv6-user-flow-routing-helper.cc',
        'model/flow-connection-manager.cc',
        'helper/flow-connection-manager-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('pmipv6')
    module_test.source = [
        'test/pmipv6-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'pmipv6'
    headers.source = [
        'model/binding-cache.h',
        'model/binding-update-list.h',
        'model/identifier.h',
        'model/ipv6-mobility-demux.h',
        'model/ipv6-mobility.h',
        'model/ipv6-mobility-header.h',
        'model/ipv6-mobility-l4-protocol.h',
        'model/ipv6-mobility-option-demux.h',
        'model/ipv6-mobility-option.h',
        'model/ipv6-mobility-option-header.h',
        'model/ipv6-static-source-routing.h',
        'model/ipv6-tunnel-l4-protocol.h',
        'model/pmipv6-agent.h',
        'model/pmipv6-lma.h',
        'model/pmipv6-mag.h',
        'model/pmipv6-mag-notifier.h',
        'model/pmipv6-prefix-pool.h',
        'model/pmipv6-profile.h',
        'model/tunnel-net-device.h',
        'model/unicast-radvd.h',
        'model/unicast-radvd-interface.h',
        'model/regular-unicast-radvd.h',
        'model/lte-unicast-radvd.h',
        'model/flow-binding-list.h',
        'model/flow-interface-list.h',
        'model/traffic-selector.h',
        'model/ipv6-flow-routing.h',
        'model/ipv6-user-flow-routing.h',
        'model/flow-manager.h',
        'helper/ipv6-static-source-routing-helper.h',
        'helper/pmipv6-helper.h',
        'helper/ipv6-flow-routing-helper.h',
        'helper/ipv6-user-flow-routing-helper.h',
        'model/flow-connection-manager.h',
        'helper/flow-connection-manager-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

